package drlg

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"
	"unsafe"
)

// update rewrites the goldens this package generates itself. It deliberately does NOT touch
// testdata/roomdump_*, which comes from the Zig CLI: a golden the bindings can rewrite is a
// golden that cannot catch them being wrong.
var update = flag.Bool("update", false, "rewrite the goldens generated by these bindings")

// The generated structs are filled by the native side in place, so their layout is the ABI.
// These are the sizes and offsets d2drlg.h defines; a mismatch means every list read is garbage.
func TestStructLayout(t *testing.T) {
	if got, want := unsafe.Sizeof(Room{}), uintptr(28); got != want {
		t.Errorf("sizeof(Room) = %d, want %d", got, want)
	}
	for _, c := range []struct {
		field string
		got   uintptr
		want  uintptr
	}{
		{"Room.X", unsafe.Offsetof(Room{}.X), 0},
		{"Room.Y", unsafe.Offsetof(Room{}.Y), 4},
		{"Room.W", unsafe.Offsetof(Room{}.W), 8},
		{"Room.H", unsafe.Offsetof(Room{}.H), 12},
		{"Room.Kind", unsafe.Offsetof(Room{}.Kind), 16},
		{"Room.PresetKind", unsafe.Offsetof(Room{}.PresetKind), 20},
		{"Room.PickedFile", unsafe.Offsetof(Room{}.PickedFile), 24},
	} {
		if c.got != c.want {
			t.Errorf("offsetof(%s) = %d, want %d", c.field, c.got, c.want)
		}
	}

	if got, want := unsafe.Sizeof(PresetUnit{}), uintptr(16); got != want {
		t.Errorf("sizeof(PresetUnit) = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(PresetUnit{}.TxtFileNo), uintptr(4); got != want {
		t.Errorf("offsetof(PresetUnit.TxtFileNo) = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(Adjacent{}), uintptr(12); got != want {
		t.Errorf("sizeof(Adjacent) = %d, want %d", got, want)
	}
}

func TestABIVersion(t *testing.T) {
	got, err := ABIVersion()
	if err != nil {
		t.Fatal(err)
	}
	if got != abiVersion {
		t.Fatalf("ABIVersion() = %d, want %d", got, abiVersion)
	}
}

// TestRoomDumpMatchesEngine reproduces the Zig CLI's `d2-drlg roomdump 28 0x10000000 0` output
// from the Go bindings and requires it byte for byte. The golden was produced by that CLI, so
// this is a cross-implementation check: it fails if the bindings misread the ABI, not merely if
// their own output changed.
func TestRoomDumpMatchesEngine(t *testing.T) {
	want := readGolden(t, "testdata/roomdump_28_0x10000000_0.txt")

	g := newGenerator(t)
	act, err := g.GenerateAct(0x10000000, Normal, 0)
	if err != nil {
		t.Fatal(err)
	}
	level := act.Level(28)
	if level == nil {
		t.Fatal("act I has no level 28 (Barracks)")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# level %d origin %d,%d size %dx%d rooms %d\n",
		level.ID, level.OriginX, level.OriginY, level.Width, level.Height, len(level.Rooms))
	for _, r := range level.Rooms {
		fmt.Fprintf(&b, "%d\t%d\t%d\t%d\t%d\t%d\n",
			r.X-level.OriginX, r.Y-level.OriginY, r.W, r.H, r.Kind, r.PresetKind)
	}

	if got := b.String(); got != want {
		t.Errorf("roomdump mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestActISnapshot pins the whole shape of a generated act: every level, its metadata and the
// counts of everything read through a separate entry point. A change in any of them shows up as
// a diff of the full snapshot rather than as a passing test with different numbers.
func TestActISnapshot(t *testing.T) {
	const golden = "testdata/act1_normal_0x10000000.txt"

	g := newGenerator(t)
	act, err := g.GenerateAct(0x10000000, Normal, 0)
	if err != nil {
		t.Fatal(err)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "seed 0x%08x %s act %d levels %d\n", act.Seed, act.Difficulty, act.Number+1, len(act.Levels))
	for _, l := range act.Levels {
		fmt.Fprintf(&b, "%3d %-28s %-11s placed=%v origin=%d,%d size=%dx%d rooms=%d npcs=%d objects=%d adjacents=%d\n",
			l.ID, l.Name, l.Type, l.Placed, l.OriginX, l.OriginY, l.Width, l.Height,
			len(l.Rooms), countKind(l.Presets, NPC), countKind(l.Presets, Object), len(l.Adjacents))
	}

	got := b.String()
	if *update {
		if err := os.WriteFile(golden, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	if want := readGolden(t, golden); got != want {
		t.Errorf("act I snapshot mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Shrines and wells are not a separate entry point: they are already among a level's presets, as
// the Objects.txt rows the outdoor spawner draws from. This is the documented way to get them,
// and the expectation is the output the root README publishes for the TypeScript binding — a
// second implementation of the same C ABI, so agreeing with it is agreement across languages.
func TestShrinesMatchPublishedExample(t *testing.T) {
	shrineRows := map[int32]string{2: "shrine", 81: "shrine", 83: "shrine", 84: "shrine", 130: "well"}

	g := newGenerator(t)
	act, err := g.GenerateAct(1337, Normal, 0)
	if err != nil {
		t.Fatal(err)
	}
	cold := act.Level(3)
	if cold == nil {
		t.Fatal("act I has no level 3 (Cold Plains)")
	}

	var got []string
	for _, p := range cold.Presets {
		if p.Kind != Object {
			continue
		}
		if kind, ok := shrineRows[p.TxtFileNo]; ok {
			// The published example reports world TILES; presets are level-local subtiles.
			got = append(got, fmt.Sprintf("%s class %d at tile (%d, %d)",
				kind, p.TxtFileNo, cold.OriginX+p.X/5, cold.OriginY+p.Y/5))
		}
	}

	want := []string{
		"shrine class 2 at tile (995, 1124)",
		"shrine class 84 at tile (994, 1114)",
		"shrine class 81 at tile (1050, 1098)",
		"well class 130 at tile (1010, 1091)",
		"shrine class 83 at tile (1002, 1090)",
	}
	if len(got) != len(want) {
		t.Fatalf("Cold Plains shrines/wells at seed 1337:\n got %v\nwant %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("shrine %d = %q, want %q", i, got[i], want[i])
		}
	}
}

// The collision and walk grids are the two big optional copies, and the walk grid is derived
// from the collision one, so they have to agree: a cell the walk grid calls walkable must not
// carry a blocking flag in the raw CollMap.
func TestCollisionAndWalkAgree(t *testing.T) {
	g := newGenerator(t)
	act, err := g.GenerateAct(0x10000000, Normal, 0, WithCollision(), WithWalk())
	if err != nil {
		t.Fatal(err)
	}
	level := act.Level(2) // Blood Moor, an outdoor level with a real grid
	if level == nil {
		t.Fatal("act I has no level 2 (Blood Moor)")
	}
	if level.Collision == nil || level.Walk == nil {
		t.Fatalf("collision=%v walk=%v, want both", level.Collision != nil, level.Walk != nil)
	}
	if level.Collision.Width != level.Walk.Width || level.Collision.Height != level.Walk.Height {
		t.Fatalf("grid dims differ: collision %dx%d, walk %dx%d",
			level.Collision.Width, level.Collision.Height, level.Walk.Width, level.Walk.Height)
	}
	if want := level.Width * 5; level.Collision.Width != want {
		t.Errorf("collision width = %d, want the level's %d tiles in subtiles (%d)",
			level.Collision.Width, level.Width, want)
	}

	// The mask the walk grid is derived with: blocked terrain, player-blocked, or an object.
	const blocking = Wall | NoPlayer | ObjectBit
	walkable := 0
	for y := int32(0); y < level.Walk.Height; y++ {
		for x := int32(0); x < level.Walk.Width; x++ {
			c := level.Collision.At(x, y)
			if !level.Walk.At(x, y) {
				continue
			}
			walkable++
			if c == Void || c&blocking != 0 {
				t.Fatalf("subtile %d,%d is walkable but its CollMap cell is 0x%04x", x, y, c)
			}
		}
	}
	if walkable == 0 {
		t.Error("no walkable subtile in the Blood Moor")
	}
}

// A generator with no act generated still answers table lookups, and a closed one answers
// nothing. Close is idempotent because a deferred Close after an explicit one is normal Go.
func TestLifecycle(t *testing.T) {
	g, err := New()
	if err != nil {
		t.Fatal(err)
	}
	if got := g.levelName(1); got != "Rogue Encampment" {
		t.Errorf("levelName(1) = %q, want %q", got, "Rogue Encampment")
	}
	if g.Core() == 0 {
		t.Error("Core() on an open generator is 0")
	}
	if err := g.Close(); err != nil {
		t.Fatal(err)
	}
	if err := g.Close(); err != nil {
		t.Fatalf("second Close: %v", err)
	}
	if g.Core() != 0 {
		t.Error("Core() on a closed generator is not 0")
	}
	if _, err := g.GenerateAct(1, Normal, 0); err != ErrClosed {
		t.Errorf("GenerateAct after Close = %v, want %v", err, ErrClosed)
	}
}

func TestGenerateActRejectsBadAct(t *testing.T) {
	g := newGenerator(t)
	for _, act := range []int{-1, 5, 99} {
		if _, err := g.GenerateAct(1, Normal, act); err == nil {
			t.Errorf("GenerateAct(act=%d) succeeded, want an error", act)
		}
	}
}

func TestObjectName(t *testing.T) {
	if _, err := New(); err != nil { // the tables have to be loaded for the object columns
		t.Fatal(err)
	}
	name, err := ObjectName(2)
	if err != nil {
		t.Fatal(err)
	}
	if name == "" {
		t.Error("ObjectName(2) is empty")
	}
}

// All five acts generate, which is the cheapest guard against a level index the bindings walk
// off the end of.
func TestAllActs(t *testing.T) {
	g := newGenerator(t)
	for act := 0; act < 5; act++ {
		a, err := g.GenerateAct(0x10000000, Hell, act)
		if err != nil {
			t.Fatalf("act %d: %v", act+1, err)
		}
		if len(a.Levels) == 0 {
			t.Fatalf("act %d generated no levels", act+1)
		}
		for _, l := range a.Levels {
			if l.ID <= 0 {
				t.Fatalf("act %d has a level with id %d", act+1, l.ID)
			}
		}
	}
}

// One generator per goroutine is the documented way to parallelise, and it is also the case
// that would show up any trouble with calling into the library from several OS threads at once —
// purego has no cgo call boundary doing that for us.
func TestConcurrentGenerators(t *testing.T) {
	want, err := newGenerator(t).GenerateAct(0x10000000, Normal, 0)
	if err != nil {
		t.Fatal(err)
	}

	const workers = 8
	errs := make(chan error, workers)
	for i := 0; i < workers; i++ {
		go func() {
			g, err := New()
			if err != nil {
				errs <- err
				return
			}
			defer g.Close()
			got, err := g.GenerateAct(0x10000000, Normal, 0)
			if err != nil {
				errs <- err
				return
			}
			if len(got.Levels) != len(want.Levels) {
				errs <- fmt.Errorf("generated %d levels, want %d", len(got.Levels), len(want.Levels))
				return
			}
			for i := range want.Levels {
				if got.Levels[i].ID != want.Levels[i].ID ||
					len(got.Levels[i].Rooms) != len(want.Levels[i].Rooms) {
					errs <- fmt.Errorf("level %d differs from the single-threaded generation", want.Levels[i].ID)
					return
				}
			}
			errs <- nil
		}()
	}
	for i := 0; i < workers; i++ {
		if err := <-errs; err != nil {
			t.Error(err)
		}
	}
}

// What a whole act costs, which is the only number that matters for choosing between calling the
// native library and not: generation itself dominates, and the per-call FFI overhead does not
// show up at this granularity.
func BenchmarkGenerateAct(b *testing.B) {
	g, err := New()
	if err != nil {
		b.Fatal(err)
	}
	defer g.Close()
	for i := 0; b.Loop(); i++ {
		if _, err := g.GenerateAct(uint32(i), Normal, 0); err != nil {
			b.Fatal(err)
		}
	}
}

// The same act with every level's collision grid copied out, which is where the cost moves from
// generating to crossing the boundary.
func BenchmarkGenerateActWithCollision(b *testing.B) {
	g, err := New()
	if err != nil {
		b.Fatal(err)
	}
	defer g.Close()
	for i := 0; b.Loop(); i++ {
		if _, err := g.GenerateAct(uint32(i), Normal, 0, WithCollision()); err != nil {
			b.Fatal(err)
		}
	}
}

// A single trivial call, to price the FFI boundary itself.
func BenchmarkABIVersion(b *testing.B) {
	a, err := load()
	if err != nil {
		b.Fatal(err)
	}
	for b.Loop() {
		_ = a.abiVersion()
	}
}

func countKind(units []PresetUnit, kind PresetKind) int {
	n := 0
	for _, u := range units {
		if u.Kind == kind {
			n++
		}
	}
	return n
}

func newGenerator(t *testing.T) *Generator {
	t.Helper()
	g, err := New()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { g.Close() })
	return g
}

func readGolden(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}
