#pragma once
/*
 * d2pf — C ABI for routing over faithful D2 1.14d maps.
 * ABI version 2. See d2pf_abi_version().
 *
 * Routes from anywhere to anywhere across a generated act: the level graph first, then a path
 * inside each level, returned as one leg per level with the exit taken out of it.
 *
 * THIS LIBRARY DOES NOT GENERATE MAPS. It routes over a world generated by d2drlg, and takes
 * that generator's context (D2DrlgCtx *) directly, so both halves share one set of loaded
 * tables and one generated act. Link it together with d2drlg — in the combined WebAssembly
 * build they already share a linear memory, which is the whole reason the two are one module:
 * a route is computed against the act that is already resident, with no collision data copied
 * across the boundary.
 *
 * COORDINATES. Every x/y here is a LEVEL-LOCAL subtile, the frame a level's own map data uses
 * and the one d2drlg_act_level_presets reports. Multiply a level's tile origin by 5 to convert
 * to the world frame. Levels are named by their Levels.txt id, which is stable across seeds.
 */
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* From d2drlg.h, for the doc comments below. Include d2drlg.h to actually make one. */
typedef struct D2DrlgCtx D2DrlgCtx;

/* Opaque routing world: the acts loaded into it and the collision maps built per level. */
typedef struct D2PfWorld D2PfWorld;

/* Opaque computed route. Free with d2pf_route_free. */
typedef struct D2PfRoute D2PfRoute;

/* How a move is made. */
enum {
    D2PF_MOVE_WALK     = 0,
    /* A teleport cast. x/y is where you land. */
    D2PF_MOVE_TELEPORT = 1,
    /*
     * Arrived by stepping on a teleport pad (the Arcane Sanctuary ones). x/y is where you COME
     * OUT; the PREVIOUS move is the pad you stepped on. A consumer walks to the previous move
     * and then finds itself at this one.
     */
    D2PF_MOVE_PAD      = 2
};

/* One step of a route, in level-local subtiles. `kind` is one of D2PF_MOVE_*. */
typedef struct D2PfMove {
    int32_t x;
    int32_t y;
    int32_t kind;
} D2PfMove;

/* Which distance metric bounds a teleport cast. */
enum {
    /* The engine's own per-axis test, max(|dx|,|dy|). */
    D2PF_METRIC_CHEBYSHEV = 0,
    /* The radial cap conventional bots apply. Strictly more conservative. */
    D2PF_METRIC_EUCLIDEAN = 1
};

/*
 * Routing options. Do NOT zero-initialise this and hope: a zeroed struct means "no collision
 * mask, no cast limit", which is not a sane default. Call d2pf_options_default first, then
 * change what you mean to change.
 */
typedef struct D2PfOptions {
    /* Movement collision model. The default is what a walking player uses. */
    uint16_t mask;
    /* Teleport where the level permits it. Levels that forbid it fall back to walking. */
    int32_t teleport;
    /*
     * Cross a level boundary with a single cast where the engine allows one. Requires
     * `teleport`. Off by default because it depends on the destination room being LOADED
     * server-side: a planned cast into a room the server has not allocated silently does
     * nothing. Turn it on when the whole act is resident.
     */
    int32_t teleport_across_levels;
    /*
     * Maximum cast distance in subtiles, the gate the packet handler applies. Defaults to the
     * engine's 50; lower it for margin against position lag. NEGATIVE drops the distance gate
     * and leaves only the adjacent-room rule.
     */
    int32_t teleport_max_cast;
    /* One of D2PF_METRIC_*. */
    int32_t teleport_metric;
    /* Accept a passable cell this far from a blocked start or goal. */
    int32_t snap_radius;
} D2PfOptions;

/* Fill `out` with the engine defaults. Always call this before changing fields. */
void d2pf_options_default(D2PfOptions *out);

/*
 * Create a routing world over a d2drlg context. difficulty: 0=normal 1=nightmare 2=hell.
 * Returns NULL on failure.
 *
 * `drlg_ctx_core` is what `d2drlg_ctx_core(ctx)` returns, NOT the D2DrlgCtx handle itself:
 *
 *     D2DrlgCtx *ctx = d2drlg_ctx_create();
 *     D2PfWorld *w   = d2pf_world_create(d2drlg_ctx_core(ctx), seed, 0);
 *
 * It is typed void * rather than D2DrlgCtx * so that passing the handle by mistake is a
 * compile error instead of a crash — C would convert a D2DrlgCtx * silently.
 *
 * The context must outlive the world.
 */
D2PfWorld *d2pf_world_create(void *drlg_ctx_core, uint32_t seed, int32_t difficulty);

/* Frees a world (NULL-safe). Routes taken from it are independent and outlive it. */
void d2pf_world_destroy(D2PfWorld *world);

/*
 * Generate an act into the world and index its levels. act_no is 0-based (Act I = 0). Load
 * every act you intend to route across. Returns 0, or a negative error code.
 */
int32_t d2pf_world_load_act(D2PfWorld *world, int32_t act_no);

/*
 * Route between two level-local positions. `opts` may be NULL for the defaults.
 *
 * Positions are scalars rather than by-value structs deliberately: a struct argument becomes a
 * hidden pointer on the wasm C ABI, which a JavaScript host cannot see. Scalars mean every host
 * calls this the same way. Returns a route handle to
 * free with d2pf_route_free, or NULL if no route exists (which is an ANSWER, not an error:
 * some pairs genuinely are not connected).
 */
D2PfRoute *d2pf_route(D2PfWorld *world,
                      int32_t from_level, int32_t from_x, int32_t from_y,
                      int32_t to_level, int32_t to_x, int32_t to_y,
                      const D2PfOptions *opts);

/* Frees a route (NULL-safe). */
void d2pf_route_free(D2PfRoute *route);

/* Number of legs (one per level crossed), or -1 on error. */
int32_t d2pf_route_leg_count(D2PfRoute *route);

/* Total moves across every leg — a cheap way to compare two routes. -1 on error. */
int32_t d2pf_route_move_count(D2PfRoute *route);

/* Levels.txt id of a leg's level, or -1 if out of range. */
int32_t d2pf_route_leg_level(D2PfRoute *route, int32_t leg);

/*
 * The level a leg exits into, or -1 if this leg has no exit (the last one). A transition always
 * runs from this leg's LAST move to the next leg's FIRST move — true for a staircase, an area
 * border and a teleport cast alike — so a consumer never special-cases where the far side is.
 */
int32_t d2pf_route_leg_exit(D2PfRoute *route, int32_t leg);

/*
 * Writes up to `cap` of a leg's moves into `out`; returns the FULL move count for that leg
 * (>=0, may exceed `cap` => truncated) or a negative error code.
 */
int32_t d2pf_route_leg_moves(D2PfRoute *route, int32_t leg, D2PfMove *out, int32_t cap);

/*
 * The level graph only: writes up to `cap` Levels.txt ids of the levels crossed to get from
 * `from` to `to`, without pathing inside any of them. Cheap enough to call in a loop when you
 * only need to know WHICH areas a trip passes. Returns the FULL count (>=0, may exceed `cap`)
 * or a negative error code.
 */
int32_t d2pf_level_route(D2PfWorld *world, int32_t from, int32_t to, int32_t *out, int32_t cap);

/* 1 if a walking player fits at this level-local subtile, 0 if not, negative on error. */
int32_t d2pf_walkable(D2PfWorld *world, int32_t level_id, int32_t x, int32_t y);

/*
 * 1 if line of sight runs between two level-local subtiles, 0 if not, negative on error.
 * `mask` selects what blocks sight; pass 0 for the default the engine uses for a cast.
 */
int32_t d2pf_line_of_sight(D2PfWorld *world, int32_t level_id,
                           int32_t from_x, int32_t from_y, int32_t to_x, int32_t to_y,
                           uint16_t mask);

/*
 * The nearest cell to (x,y) that a walking player fits in, searched outward to `radius`.
 * Writes it to *out_x / *out_y and returns 1; returns 0 if nothing within radius is passable,
 * or a negative error code. This is what to call before routing to a spot that may be inside
 * a wall — a monster's reported position often is.
 */
int32_t d2pf_nearest_passable(D2PfWorld *world, int32_t level_id, int32_t x, int32_t y,
                              int32_t radius, int32_t *out_x, int32_t *out_y);

/*
 * THE LIVE WORLD.
 *
 * Everything above answers from the map as it was generated. A running game also has units
 * standing on it, and the engine keeps them in the same collision grid: a unit ORs its bits into
 * the cells it covers when it arrives and clears them when it leaves. Register them here and every
 * query above — walkability, routing, line of sight, nearest-passable — sees them.
 *
 * `unit_type` is eD2UnitType: 0 player, 1 monster, 2 object, 4 item, 5 room tile. `size_x` is the
 * unit's GetUnitSizeX (0..3). Between them they decide which cells are claimed and with which bit,
 * exactly as the engine decides it when it allocates the unit's path — a big monster covers a 3x3
 * box, an item covers its cell and blocks nobody.
 *
 * Calling place() again for an id that is already down MOVES it: the cells it used to cover go
 * back to what the rest of the world says about them, not to blank.
 *
 * Returns 0, or a negative error code.
 */
int32_t d2pf_unit_place(D2PfWorld *world, int32_t level_id, uint32_t unit_id, uint8_t unit_type,
                        int32_t size_x, int32_t x, int32_t y);

/* Take a unit off the level, restoring every cell it covered. */
int32_t d2pf_unit_lift(D2PfWorld *world, int32_t level_id, uint32_t unit_id);

/* Empty a level's live world — leaving the game, or resyncing from scratch. */
int32_t d2pf_units_clear(D2PfWorld *world, int32_t level_id);

/*
 * TERRAIN itself changed over an inclusive subtile rectangle: a door opened, a quest barrier
 * dropped. `add` and `remove` are raw COLBIT masks (0x01 wall, 0x800 door, ...).
 *
 * This is not the same thing as a unit and is far more expensive: it rewrites the generated grid
 * and throws away the reachability caches built on it, because unlike a unit it can make a cell
 * MORE passable and so join two regions. Call it for the handful of events per game that really
 * change the map; call d2pf_unit_place for everything that merely stands on it.
 */
int32_t d2pf_terrain_edit(D2PfWorld *world, int32_t level_id, int32_t x0, int32_t y0,
                          int32_t x1, int32_t y1, uint16_t add, uint16_t remove);

/* Returns the ABI version (currently 2). */
uint32_t d2pf_abi_version(void);

#ifdef __cplusplus
}
#endif
