//! The server-to-client framing table, per engine build.
//!
//! `sc.zig` carries 1.14d's. This file carries every OTHER build's, read out of that build's own
//! D2Net.dll rather than assumed to match a neighbour -- generated by scripts/gen_sc_versions.py.
//!
//! It is worth saying plainly what this file exists to stop, because the cost of not having it was
//! paid twice. `0x01` GameFlags is SIX bytes on 1.06b, SEVEN on 1.07 through 1.09, and EIGHT from
//! 1.10f on. Frame it with a table one byte too long and it swallows the `0x02` LoadSuccess sitting
//! behind it, and the client then waits forever for a handshake the server already sent. There is
//! no error and nothing in the log: it is a hang, and it looks exactly like a server that never
//! answered. Every build before 1.10f fails this way against a 1.14d table.
//!
//! A build is in here because its table was read. Nothing is inferred from the build next to it --
//! that assumption is what made the old two-era model wrong in both directions at once.

const std = @import("std");
const sc = @import("sc.zig");

/// The builds whose S->C table has actually been read.
pub const Version = enum {
    v106b,
    v107,
    v108,
    v109b,
    v109d,
    v110f,
    v113c,
    /// `sc.SC_SIZE`. Here so callers can name every build the same way.
    v114d,
};


/// Read from 1.06b's D2Net.dll at file offset 0x813c, 157 entries (0x00..0x9c).
/// 44 differ from 1.14d's.
pub const packet_size_106b = [0x9d]i16{
    1, 6, 1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16, // 0x00
    16, 8, 26, 14, 18, 11, -1, 0, 15, 2, 2, 3, 5, 3, 4, 6, // 0x10
    10, 12, 12, 9, 90, 90, -1, 40, 103, 97, 15, 0, 8, 68, 68, 68, // 0x20
    68, 68, 68, 68, 68, 68, 68, 68, 45, 45, 68, 68, 68, 68, 11, 8, // 0x30
    13, 68, 6, 68, 68, 13, 68, 11, 11, 68, 68, 0, 16, 15, 7, 1, // 0x40
    15, 14, 37, 10, 3, 13, 46, 14, 7, 26, 40, -1, 5, 5, 31, 5, // 0x50
    7, 2, 7, 21, 0, 7, 7, 15, 20, 12, 12, 16, 16, 10, 1, 1, // 0x60
    1, 1, 1, 33, 10, 13, 6, 2, 21, 6, 13, 4, 6, 18, 5, 9, // 0x70
    0, 20, 29, 0, 0, 8, 0, 0, 0, 2, 6, 6, 11, 7, 10, 33, // 0x80
    13, 26, 6, 8, -1, 13, 9, -1, 1, 0, 53, -1, 5, // 0x90
};

/// Read from 1.07's D2Net.dll at file offset 0x813c, 173 entries (0x00..0xac).
/// 41 differ from 1.14d's.
pub const packet_size_107 = [0xad]i16{
    1, 7, 1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16, // 0x00
    16, 9, 26, 14, 18, 11, -1, 0, 15, 2, 2, 3, 5, 3, 4, 6, // 0x10
    10, 12, 12, 13, 90, 90, -1, 40, 103, 97, 15, 0, 8, 68, 68, 68, // 0x20
    68, 68, 68, 68, 68, 68, 68, 68, 45, 45, 68, 68, 68, 68, 11, 8, // 0x30
    13, 68, 6, 68, 68, 13, 68, 11, 11, 68, 68, 0, 16, 15, 7, 1, // 0x40
    15, 14, 42, 10, 3, 13, 46, 14, 7, 26, 40, -1, 5, 5, 38, 5, // 0x50
    7, 2, 7, 21, 0, 7, 7, 15, 20, 12, 12, 16, 16, 10, 1, 1, // 0x60
    1, 1, 1, 33, 10, 13, 6, 2, 21, 6, 13, 8, 6, 18, 5, 10, // 0x70
    0, 20, 29, 0, 0, 8, 0, 0, 0, 2, 6, 6, 11, 7, 10, 33, // 0x80
    13, 26, 6, 8, -1, 13, 9, 1, 7, 16, 15, 7, -1, -1, 7, 8, // 0x90
    10, 7, 8, 24, 3, 8, -1, -1, 1, 0, 53, -1, 5, // 0xa0
};

/// Read from 1.08's D2Net.dll at file offset 0x813c, 173 entries (0x00..0xac).
/// 17 differ from 1.14d's.
pub const packet_size_108 = [0xad]i16{
    1, 7, 1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16, // 0x00
    16, 9, 26, 14, 18, 11, -1, 0, 15, 2, 2, 3, 5, 3, 4, 6, // 0x10
    10, 12, 12, 13, 90, 90, -1, 40, 103, 97, 15, 0, 8, 0, 0, 0, // 0x20
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 8, // 0x30
    13, 0, 6, 0, 0, 13, 0, 11, 11, 0, 0, 0, 16, 15, 7, 1, // 0x40
    15, 14, 42, 10, 3, 13, 46, 14, 7, 26, 40, -1, 5, 5, 38, 5, // 0x50
    7, 2, 7, 21, 0, 7, 7, 15, 20, 12, 12, 16, 16, 10, 1, 1, // 0x60
    1, 1, 1, 33, 10, 13, 6, 2, 21, 6, 13, 8, 6, 18, 5, 10, // 0x70
    0, 20, 29, 0, 0, 0, 0, 0, 0, 2, 6, 6, 11, 7, 10, 33, // 0x80
    13, 26, 6, 8, -1, 13, 9, 1, 7, 16, 15, 7, -1, -1, 7, 8, // 0x90
    10, 7, 8, 24, 3, 8, -1, -1, 1, 0, 53, -1, 5, // 0xa0
};

/// Read from 1.09b's D2Net.dll at file offset 0x813c, 173 entries (0x00..0xac).
/// 41 differ from 1.14d's.
pub const packet_size_109b = [0xad]i16{
    1, 7, 1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16, // 0x00
    16, 9, 26, 14, 18, 11, -1, 0, 15, 2, 2, 3, 5, 3, 4, 6, // 0x10
    10, 12, 12, 13, 90, 90, -1, 40, 103, 97, 15, 0, 8, 16384, 16384, 16384, // 0x20
    16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 11, 8, // 0x30
    13, 16384, 6, 16384, 16384, 13, 16384, 11, 11, 16384, 16384, 0, 16, 15, 7, 1, // 0x40
    15, 14, 42, 10, 3, 13, 46, 14, 7, 26, 40, -1, 5, 5, 38, 5, // 0x50
    7, 2, 7, 21, 0, 7, 7, 15, 20, 12, 12, 16, 16, 10, 1, 1, // 0x60
    1, 1, 1, 16416, 10, 13, 6, 2, 21, 6, 13, 8, 6, 18, 5, 10, // 0x70
    0, 20, 29, 0, 0, 16384, 0, 0, 0, 2, 6, 6, 11, 7, 10, 33, // 0x80
    13, 26, 6, 8, -1, 13, 9, 1, 7, 16, 15, 7, -1, -1, 7, 8, // 0x90
    10, 7, 8, 24, 3, 8, -1, -1, 1, 0, 53, -1, 5, // 0xa0
};

/// Read from 1.09d's D2Net.dll at file offset 0x8138, 173 entries (0x00..0xac).
/// 41 differ from 1.14d's.
pub const packet_size_109d = [0xad]i16{
    1, 7, 1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16, // 0x00
    16, 9, 26, 14, 18, 11, -1, 0, 15, 2, 2, 3, 5, 3, 4, 6, // 0x10
    10, 12, 12, 13, 90, 90, -1, 40, 103, 97, 15, 0, 8, 16384, 16384, 16384, // 0x20
    16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 16384, 11, 8, // 0x30
    13, 16384, 6, 16384, 16384, 13, 16384, 11, 11, 16384, 16384, 0, 16, 15, 7, 1, // 0x40
    15, 14, 42, 10, 3, 13, 46, 14, 7, 26, 40, -1, 5, 5, 38, 5, // 0x50
    7, 2, 7, 21, 0, 7, 7, 15, 20, 12, 12, 16, 16, 10, 1, 1, // 0x60
    1, 1, 1, 16416, 10, 13, 6, 2, 21, 6, 13, 8, 6, 18, 5, 10, // 0x70
    0, 20, 29, 0, 0, 16384, 0, 0, 0, 2, 6, 6, 11, 7, 10, 33, // 0x80
    13, 26, 6, 8, -1, 13, 9, 1, 7, 16, 15, 7, -1, -1, 7, 8, // 0x90
    10, 7, 8, 24, 3, 8, -1, -1, 1, 0, 53, -1, 5, // 0xa0
};

/// Read from 1.10f's D2Net.dll at file offset 0x8148, 180 entries (0x00..0xb3).
/// 6 differ from 1.14d's.
pub const packet_size_110f = [0xb4]i16{
    1, 8, 1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16, // 0x00
    16, 8, 26, 14, 18, 11, -1, 0, 15, 2, 2, 3, 5, 3, 4, 6, // 0x10
    10, 12, 12, 13, 90, 90, -1, 40, 103, 97, 15, 0, 8, 0, 0, 0, // 0x20
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 8, // 0x30
    13, 0, 6, 0, 0, 13, 0, 11, 11, 0, 0, 0, 16, 17, 7, 1, // 0x40
    15, 14, 42, 10, 3, 0, 0, 14, 7, 26, 40, -1, 5, 6, 38, 5, // 0x50
    7, 2, 7, 21, 0, 7, 7, 16, 21, 12, 12, 16, 16, 10, 1, 1, // 0x60
    1, 1, 1, 32, 10, 13, 6, 2, 21, 6, 13, 8, 6, 18, 5, 10, // 0x70
    0, 20, 29, 0, 0, 0, 0, 0, 0, 2, 6, 6, 11, 7, 10, 33, // 0x80
    13, 26, 6, 8, -1, 13, 9, 1, 7, 16, 17, 7, -1, -1, 7, 8, // 0x90
    10, 7, 8, 24, 3, 8, -1, 7, -1, 7, -1, 7, -1, 9, -1, 1, // 0xa0
    0, 53, -1, 5, // 0xb0
};

/// Read from 1.13c's D2Net.dll at file offset 0xa900, 182 entries (0x00..0xb5).
/// 0 differ from 1.14d's.
pub const packet_size_113c = [0xb6]i16{
    1, 8, 1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16, // 0x00
    16, 8, 26, 14, 18, 11, -1, 0, 15, 2, 2, 3, 5, 3, 4, 6, // 0x10
    10, 12, 12, 13, 90, 90, -1, 40, 103, 97, 15, 0, 8, 0, 0, 0, // 0x20
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 8, // 0x30
    13, 0, 6, 0, 0, 13, 0, 11, 11, 0, 0, 0, 16, 17, 7, 1, // 0x40
    15, 14, 42, 10, 3, 0, 0, 14, 7, 26, 40, -1, 5, 6, 38, 5, // 0x50
    7, 2, 7, 21, 0, 7, 7, 16, 21, 12, 12, 16, 16, 10, 1, 1, // 0x60
    1, 1, 1, 32, 10, 13, 6, 2, 21, 6, 13, 8, 6, 18, 5, 10, // 0x70
    0, 20, 29, 0, 0, 0, 0, 0, 0, 2, 6, 6, 11, 7, 10, 33, // 0x80
    13, 26, 6, 8, -1, 13, 9, 1, 7, 16, 17, 7, -1, -1, 7, 8, // 0x90
    10, 7, 8, 24, 3, 8, -1, 7, -1, 7, -1, 7, -1, 0, -1, -1, // 0xa0
    1, 0, 53, -1, 5, 0, // 0xb0
};

/// The table this build frames with.
pub fn sizeTable(v: Version) []const i16 {
    return switch (v) {
        .v106b => &packet_size_106b,
        .v107 => &packet_size_107,
        .v108 => &packet_size_108,
        .v109b => &packet_size_109b,
        .v109d => &packet_size_109d,
        .v110f => &packet_size_110f,
        .v113c => &packet_size_113c,
        .v114d => &sc.SC_SIZE,
    };
}

/// Full wire size of the S->C packet at the front of `buf` for THIS build, or null when more bytes
/// are needed to tell. 0 means the opcode is unused by this build and the stream cannot be
/// resynchronised.
///
/// The variable-length readers come from `sc.variableSize`, which is 1.14d's. Those have not been
/// read per build, and this is the honest limit of this file: the fixed sizes are measured, the
/// handful of variable ones are 1.14d's rules applied to an older build. They are a small minority
/// of the table and none of them is on the join path.
pub fn packetSize(v: Version, buf: []const u8) ?usize {
    if (buf.len == 0) return null;
    const t = sizeTable(v);
    const op = buf[0];
    if (op >= t.len) return 0;
    const n = t[op];
    if (n == 0) return 0;
    if (n > 0) {
        const need: usize = @intCast(n);
        return if (buf.len >= need) need else null;
    }
    const need = sc.variableSize(op, buf) orelse return null;
    return if (buf.len >= need) need else null;
}

test "GameFlags is the entry that moves: six, seven, then eight" {
    // The whole reason this file exists. A build framed with the next one's table hangs.
    try std.testing.expectEqual(@as(i16, 6), sizeTable(.v106b)[0x01]);
    try std.testing.expectEqual(@as(i16, 7), sizeTable(.v107)[0x01]);
    try std.testing.expectEqual(@as(i16, 8), sizeTable(.v110f)[0x01]);
    try std.testing.expectEqual(@as(i16, 8), sizeTable(.v114d)[0x01]);
}

test "the LoadSuccess behind GameFlags survives, on every build" {
    // GameFlags and the 0x02 LoadSuccess arriving in one read: framing the first one byte too long
    // eats the second, and the client waits for a handshake it has already been sent.
    for ([_]struct { v: Version, n: usize }{
        .{ .v = .v106b, .n = 6 },
        .{ .v = .v107, .n = 7 },
        .{ .v = .v110f, .n = 8 },
    }) |c| {
        var wire = [_]u8{ 0x01, 1, 2, 3, 4, 5, 6, 7, 0x02 };
        wire[c.n] = 0x02;
        try std.testing.expectEqual(@as(?usize, c.n), packetSize(c.v, wire[0 .. c.n + 1]));
        try std.testing.expectEqual(@as(?usize, 1), packetSize(c.v, wire[c.n .. c.n + 1]));
    }
}

test "a partial packet asks for more bytes rather than guessing" {
    try std.testing.expectEqual(@as(?usize, null), packetSize(.v110f, &[_]u8{ 0x01, 1, 2 }));
    try std.testing.expectEqual(@as(?usize, null), packetSize(.v106b, &[_]u8{}));
}

test "an opcode past a build's table is a desync, not a wrap" {
    // 1.06b's table is shorter than 1.14d's. An opcode it does not know must report 0 rather than
    // index off the end of the array.
    const high: u8 = @intCast(sizeTable(.v106b).len);
    try std.testing.expectEqual(@as(?usize, 0), packetSize(.v106b, &[_]u8{high}));
}
