//! Engine skill vocabulary owned by d2-core — currently the server do-function index.
//!
//! Pure constants (no logic, no deps): the same role as the collision/stat vocabularies that live
//! here so every consumer shares one source of truth instead of vendoring the numbers. The behaviour
//! that reads these (SkillData.kind/serverMissile/…) stays in d2-sim; only the NAMED value space is
//! here. Pure Zig, libc-free.

const std = @import("std");

/// The engine's server-skill do-function index (Skills.txt `srvdofunc`): the value that selects
/// which `SKILLSRVDOFUNCS[]` handler the 1.14d engine runs (dispatcher SKILLS_DispatchSrvDoFunc
/// @0x56d810, 191-entry table @0x7322b0, indices 1..152 populated). Every populated index is named
/// after its engine function so a branch can be self-documenting.
///
/// These names follow the SKILL that uses each srvdofunc — the authoritative mapping is Skills.txt,
/// which IS the engine's runtime dispatch data (a skill row's `srvdofunc` selects SKILLSRVDOFUNCS[N]).
/// CAUTION: several of Ghidra's auto-named `Skills_SrvDoFunc_NNN_*` symbols DISAGREE with that data and
/// are misnamed — verified from Skills.txt: 44=Blade Sentinel, 45=trap sentries (Lightning/Death
/// Sentry), 48=Blade Fury, 49=Shadow Warrior/Master, 56=golems (Clay/Blood/Fire), 60=Bone Wall,
/// 62=Bone Prison, 117=Firestorm, 118=Twister/Tornado. (117/118 were corrected in Ghidra v630; the
/// rest still carry Ghidra's wrong symbol names — do NOT trust the Ghidra label, trust Skills.txt +
/// the function body reached THROUGH the table index, not through the symbol name.)
pub const DoFunc = enum(i32) {
    none = 0,
    attack = 1,
    apply_aura_on_hit = 2,
    throw_weapon_left_hand = 3,
    remove_pet_by_skill_param = 4,
    throw_weapon_right_hand = 5,
    phoenix_strike_area_bolt = 6,
    power_strike_melee_hit = 7,
    strafe_missile_spread = 8,
    frenzy_melee_hit = 9,
    guided_arrow_launch = 10,
    charged_strike = 11,
    strafe_continue = 12,
    impale_or_fend_hit = 13,
    phoenix_strike_charged_release = 14,
    summon_decoy = 15,
    summon_valkyrie = 16,
    charged_bolt = 17,
    armor = 18,
    inferno = 19,
    static = 20,
    telekinesis = 21,
    nova_frost_nova = 22,
    blaze_energy_shield = 23,
    fire_wall = 24,
    enchant = 25,
    chain_lightning = 26,
    teleport = 27,
    meteor_blizzard = 28,
    thunder_storm = 29,
    cast_curse_aoe = 30,
    raise_from_corpse = 31,
    apply_direct_damage = 32,
    tiger_strike = 33,
    charge_up_stack_melee = 34,
    dragon_claw = 35,
    charge_release_missile_ring = 36,
    charge_release_multi_element_scatter = 37,
    dragon_tail_kick_aoe = 38,
    charge_release_circle_spawn = 39,
    charge_release_single_missile = 40,
    blade_fury_scatter = 41,
    dragon_talon = 42,
    charge_release_scatter_missiles = 43,
    blade_sentinel = 44,
    summon_trap_sentry = 45,
    cobra_strike = 46,
    cloak_of_shadows = 47,
    blade_fury = 48,
    summon_shadow_clone = 49,
    dragon_tail_fire_explosion = 50,
    mind_blast_psychic_hammer = 51,
    dragon_flight = 52,
    venom_blade_shield_area_pulse = 53,
    blade_shield_activate = 54,
    corpse_explosion = 55,
    summon_golem = 56,
    iron_golem = 57,
    revive_corpse_check = 58,
    cast_corpse_skill = 59,
    summon_bone_wall = 60,
    cast_convert_aoe = 61,
    spawn_bone_structure = 62,
    corpse_radial_missiles = 63,
    sacrifice = 64,
    prayer_aura = 65,
    conviction_aura = 66,
    charge = 67,
    war_cry = 68,
    find_potion = 69,
    find_item = 70,
    iron_maiden_generic_curse = 71,
    find_gold = 72,
    fist_of_the_heavens = 73,
    double_throw = 74,
    grim_ward = 75,
    leap_attack = 76,
    leap_attack_impact = 77,
    whirlwind = 78,
    conversion = 79,
    smite_80 = 80,
    holy_freeze_aura = 81,
    holy_shock_aura = 82,
    monster_melee_attack = 83,
    spawn_minions_and_suicide = 84,
    fire_upgraded_missile = 85,
    self_heal = 86,
    spawn_behind_target = 87,
    fire_missile_from_body_part = 88,
    charge_leap_attack = 89,
    set_anim_frame_from_calc = 90,
    spawn_minion_at_coords = 91,
    melee_attack_with_missile_wrapper = 92,
    fire_leading_missile = 93,
    reset_anim_frame = 94,
    spawn_trap_missile = 95,
    heal_target = 96,
    resurrect_dead_monster = 97,
    teleport_to_stored_position = 98,
    fire_missile_ring8_dir = 99,
    freezing_melee_attack = 100,
    fire_directional_missile_101 = 101,
    fire_random_multi_missile = 102,
    charge_and_melee_strike = 103,
    spawn_predefined_at_target = 104,
    fire_parallel_missile_volley = 105,
    fire_missile_ring_on_target = 106,
    leech_melee_multi_hit = 107,
    devour_minion_for_hp = 108,
    monster_frenzy_attack = 109,
    fire_arrow_mod_missile = 110,
    apply_fetish_aura = 111,
    random_curse = 112,
    use_scroll_or_book = 113,
    summon_raven = 114,
    summon_poison_creeper = 115,
    werewolf = 116,
    firestorm = 117,
    twister = 118,
    summon_dire_wolf = 119,
    feral_rage = 120,
    fury = 121,
    maul = 122,
    tornado = 123,
    armageddon = 124,
    catapult_fire_bomb = 125,
    baal_tentacle_grab = 126,
    nihlathak_corpse_explosion = 127,
    monster_create_minion = 128,
    attach_or_detach_from_host = 129,
    spawn_sub_missiles = 130,
    conditional_transform_or_buff = 131,
    fire_class_upgraded_missile = 132,
    set_death_spawn_state = 133,
    area_explosion_attack = 134,
    spawn_minion_from_params = 135,
    fire_speed_scaled_missile = 136,
    corpse_consumption_aura = 137,
    fire_perpendicular_missile_line = 138,
    fire_orthogonal_missile = 139,
    scatter_minion_spawn = 140,
    baal_corpse_explosion_wave = 141,
    blade_shield_spin_damage = 142,
    charge_release_ground_strike = 143,
    hydra = 144,
    hurricane = 145,
    cyclone_armor = 146,
    return_to_owner = 147,
    fire_missile_body_part10 = 148,
    fire_missile_body_part11 = 149,
    smite_150 = 150,
    fire_directional_missile_151 = 151,
    spawn_trap_missile_variant = 152,
    _,

    /// The engine symbol name for this do-func (for logging/tests). Unknown values render "?".
    pub fn label(self: DoFunc) []const u8 {
        return std.enums.tagName(DoFunc, self) orelse "?";
    }
};

test "DoFunc labels a known index and falls back for an unnamed one" {
    try std.testing.expectEqualStrings("hydra", DoFunc.hydra.label());
    try std.testing.expectEqualStrings("chain_lightning", (@as(DoFunc, @enumFromInt(26))).label());
    try std.testing.expectEqualStrings("?", (@as(DoFunc, @enumFromInt(153))).label());
}
