#!/usr/bin/env python3
"""Read the S->C framing table out of a build's own D2Net.dll and emit sc_versions.zig.

The table the engine frames incoming packets with lives in D2Net, not D2Client -- the same module
that carries the C->S one cs_versions.zig was read from, a little before it in the same data
section. It is an array of i32 indexed by opcode: a positive entry is the whole wire size including
the opcode byte, -1 means variable-length, 0 means the opcode is unused.

Usage:  gen_sc_versions.py <libd2-net-src> <ver>=<D2Net.dll> ...

The table is located by anchoring on opcodes 0x02..0x0f, which are identical in every build read so
far, and stepping back two entries. 0x01 is deliberately NOT in the anchor: it is the entry that
actually varies, and anchoring on a value that moves finds nothing.

The END of the table is the start of the C->S table, which cs_versions.zig already carries for that
build -- so the length is measured against another measurement rather than guessed by squinting at
where the numbers stop looking like sizes. A build whose C->S table is not in cs_versions.zig is
skipped rather than emitted with a guessed length.
"""
import struct, sys, re, os

ANCHOR = [1, 12, 1, 1, 1, 6, 6, 11, 6, 6, 9, 13, 12, 16]   # opcodes 0x02..0x0f

def zig_array(src, name):
    m = re.search(r'pub const ' + name + r'\s*=\s*\[[^\]]*\]i\d+\{(.*?)\n\};', src, re.S)
    if not m:
        return None
    return [int(x) for x in re.findall(r'-?\d+', re.sub(r'//.*', '', m.group(1)))]

def find_i32(data, vals):
    i = data.find(b''.join(struct.pack('<i', v) for v in vals))
    return None if i < 0 else i

def read(path, cs_tables):
    """cs_tables: the C->S tables cs_versions.zig carries, this build's own first.

    The end of the S->C table is the start of the C->S one. A build whose own C->S table is not in
    cs_versions.zig can still be bounded by another build's, since the leading entries are shared
    along the line -- but only when one of them is actually FOUND in this binary. That keeps it a
    measurement: an unbounded build is skipped rather than emitted with a guessed length."""
    data = open(os.path.expanduser(path), 'rb').read()
    at = find_i32(data, ANCHOR)
    if at is None:
        return None, "no S->C table (the 0x02..0x0f anchor is absent)"
    sc_off = at - 8
    for tab in cs_tables:
        if not tab:
            continue
        cs_off = find_i32(data, tab[:16])
        if cs_off is not None and cs_off > sc_off:
            n = (cs_off - sc_off) // 4
            return [struct.unpack_from('<i', data, sc_off + i * 4)[0] for i in range(n)], (sc_off, n)
    return None, "no C->S table from cs_versions.zig is present here, so the length cannot be bounded"

def emit(rows, ref):
    out = ['''//! The server-to-client framing table, per engine build.
//!
//! `sc.zig` carries 1.14d's. This file carries every OTHER build's, read out of that build's own
//! D2Net.dll rather than assumed to match a neighbour -- generated by scripts/gen_sc_versions.py.
//!
//! It is worth saying plainly what this file exists to stop, because the cost of not having it was
//! paid twice. `0x01` GameFlags is SIX bytes on 1.06b, SEVEN on 1.07 through 1.09, and EIGHT from
//! 1.10f on. Frame it with a table one byte too long and it swallows the `0x02` LoadSuccess sitting
//! behind it, and the client then waits forever for a handshake the server already sent. There is
//! no error and nothing in the log: it is a hang, and it looks exactly like a server that never
//! answered. Every build before 1.10f fails this way against a 1.14d table.
//!
//! A build is in here because its table was read. Nothing is inferred from the build next to it --
//! that assumption is what made the old two-era model wrong in both directions at once.

const std = @import("std");
const sc = @import("sc.zig");

/// The builds whose S->C table has actually been read.
pub const Version = enum {
__VERSIONS__
    /// `sc.SC_SIZE`. Here so callers can name every build the same way.
    v114d,
};
''']
    for ver, tab, meta in rows:
        off, n = meta
        d = sum(1 for i in range(min(len(tab), len(ref))) if tab[i] != ref[i])
        out.append(f'''
/// Read from {ver}'s D2Net.dll at file offset 0x{off:x}, {n} entries (0x00..0x{n-1:02x}).
/// {d} differ from 1.14d's.
pub const packet_size_{ver.replace('.','')} = [0x{n:x}]i16{{''')
        for i in range(0, len(tab), 16):
            chunk = ', '.join(f'{v}' for v in tab[i:i+16])
            out.append(f'    {chunk}, // 0x{i:02x}')
        out.append('};')
    out.append('''
/// The table this build frames with.
pub fn sizeTable(v: Version) []const i16 {
    return switch (v) {
__ARMS__        .v114d => &sc.SC_SIZE,
    };
}

/// Full wire size of the S->C packet at the front of `buf` for THIS build, or null when more bytes
/// are needed to tell. 0 means the opcode is unused by this build and the stream cannot be
/// resynchronised.
///
/// The variable-length readers come from `sc.variableSize`, which is 1.14d's. Those have not been
/// read per build, and this is the honest limit of this file: the fixed sizes are measured, the
/// handful of variable ones are 1.14d's rules applied to an older build. They are a small minority
/// of the table and none of them is on the join path.
pub fn packetSize(v: Version, buf: []const u8) ?usize {
    if (buf.len == 0) return null;
    const t = sizeTable(v);
    const op = buf[0];
    if (op >= t.len) return 0;
    const n = t[op];
    if (n == 0) return 0;
    if (n > 0) {
        const need: usize = @intCast(n);
        return if (buf.len >= need) need else null;
    }
    const need = sc.variableSize(op, buf) orelse return null;
    return if (buf.len >= need) need else null;
}

test "GameFlags is the entry that moves: six, seven, then eight" {
    // The whole reason this file exists. A build framed with the next one's table hangs.
    try std.testing.expectEqual(@as(i16, 6), sizeTable(.v106b)[0x01]);
    try std.testing.expectEqual(@as(i16, 7), sizeTable(.v107)[0x01]);
    try std.testing.expectEqual(@as(i16, 8), sizeTable(.v110f)[0x01]);
    try std.testing.expectEqual(@as(i16, 8), sizeTable(.v114d)[0x01]);
}

test "the LoadSuccess behind GameFlags survives, on every build" {
    // GameFlags and the 0x02 LoadSuccess arriving in one read: framing the first one byte too long
    // eats the second, and the client waits for a handshake it has already been sent.
    for ([_]struct { v: Version, n: usize }{
        .{ .v = .v106b, .n = 6 },
        .{ .v = .v107, .n = 7 },
        .{ .v = .v110f, .n = 8 },
    }) |c| {
        var wire = [_]u8{ 0x01, 1, 2, 3, 4, 5, 6, 7, 0x02 };
        wire[c.n] = 0x02;
        try std.testing.expectEqual(@as(?usize, c.n), packetSize(c.v, wire[0 .. c.n + 1]));
        try std.testing.expectEqual(@as(?usize, 1), packetSize(c.v, wire[c.n .. c.n + 1]));
    }
}

test "a partial packet asks for more bytes rather than guessing" {
    try std.testing.expectEqual(@as(?usize, null), packetSize(.v110f, &[_]u8{ 0x01, 1, 2 }));
    try std.testing.expectEqual(@as(?usize, null), packetSize(.v106b, &[_]u8{}));
}

test "an opcode past a build's table is a desync, not a wrap" {
    // 1.06b's table is shorter than 1.14d's. An opcode it does not know must report 0 rather than
    // index off the end of the array.
    const high: u8 = @intCast(sizeTable(.v106b).len);
    try std.testing.expectEqual(@as(?usize, 0), packetSize(.v106b, &[_]u8{high}));
}''')
    vers = ''.join(f"    v{v.replace('.', '')},\n" for v, _, _ in rows)
    arms = ''.join(f"        .v{v.replace('.', '')} => &packet_size_{v.replace('.', '')},\n"
                   for v, _, _ in rows)
    return '\n'.join(out).replace('__VERSIONS__', vers.rstrip('\n')).replace('__ARMS__', arms) + '\n'

if __name__ == '__main__':
    net = sys.argv[1]
    cs_src = open(os.path.join(net, 'cs_versions.zig')).read()
    ref = zig_array(open(os.path.join(net, 'sc.zig')).read(), 'SC_SIZE')
    rows = []
    for arg in sys.argv[2:]:
        ver, path = arg.split('=', 1)
        own = zig_array(cs_src, 'packet_size_' + ver.replace('.', ''))
        others = [zig_array(cs_src, n) for n in re.findall(r'pub const (packet_size_\w+)', cs_src)]
        tab, meta = read(path, [own] + others)
        if tab is None:
            print(f"  skipped {ver}: {meta}", file=sys.stderr); continue
        rows.append((ver, tab, meta))
        print(f"  {ver}: 0x{meta[0]:x}, {meta[1]} entries", file=sys.stderr)
    open(os.path.join(net, 'sc_versions.zig'), 'w').write(emit(rows, ref))
    print(f"wrote {os.path.join(net, 'sc_versions.zig')}", file=sys.stderr)
