#!/usr/bin/env bash
#
# Populate the Go bindings with native shared libraries + their generated embed files.
#
#   go-sync-natives.sh --local              from each package's own zig-out (host platform only)
#   go-sync-natives.sh <artifacts-root>     from the release job's build matrix
#
# Go has no equivalent of NuGet's runtimes/{rid}/native: the source IS the distribution, so the
# binary has to be in the module. Each subsystem package therefore carries
#
#   <pkg>/natives/<goos>_<goarch>/<library>       the shared library
#   <pkg>/embed_<goos>_<goarch>.go                a build-tagged //go:embed of it
#
# and a build compiles in exactly the one file matching its GOOS/GOARCH. A platform we do not
# ship simply has no such .go file, so it stays a clear runtime error instead of a build failure.
#
# <artifacts-root> is the release job's merged download, laid out by the build matrix as:
#
#   <artifacts-root>/<package>/<zig target triple>/lib/libd2<package>.so
#   <artifacts-root>/<package>/<zig target triple>/bin/d2<package>.dll
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Where the Go module lives. go-pack.sh points this at the tree it is assembling for the
# publishing mirror; everything else works on the module in place.
gomod="${GO_MODULE_DIR:-${repo_root}/packages/go/libd2}"

# libd2 package -> the Go package directory and the C library's base name.
subsystems=(
  "drlg:drlg:d2drlg"
  "item:item:d2item"
  "pathfinding:pathfinding:d2pf"
)

# zig target triple -> GOOS_GOARCH. Anything not listed is skipped rather than guessed.
#
# The musl targets have no Go equivalent — Go does not distinguish a libc — so the glibc build is
# what ships and an Alpine host points LIBD2_PATH at its own. riscv64/loong64 are absent from the
# release matrix; add them here when they appear.
goplat_for() {
  case "$1" in
    x86_64-linux-gnu)     echo "linux_amd64" ;;
    aarch64-linux-gnu)    echo "linux_arm64" ;;
    arm-linux-gnueabihf)  echo "linux_arm" ;;
    riscv64-linux-gnu)    echo "linux_riscv64" ;;
    x86_64-freebsd)       echo "freebsd_amd64" ;;
    aarch64-freebsd)      echo "freebsd_arm64" ;;
    x86_64-macos)         echo "darwin_amd64" ;;
    aarch64-macos)        echo "darwin_arm64" ;;
    x86-windows-gnu)      echo "windows_386" ;;
    x86_64-windows-gnu)   echo "windows_amd64" ;;
    aarch64-windows-gnu)  echo "windows_arm64" ;;
    *)                    echo "" ;;
  esac
}

# GOOS_GOARCH -> the shared library file name the platform's loader expects.
libfile_for() {
  case "${1%%_*}" in
    windows) echo "$2.dll" ;;
    darwin)  echo "lib$2.dylib" ;;
    *)       echo "lib$2.so" ;;
  esac
}

emit_embed() {
  local dir="$1" goplat="$2" cname="$3" libfile="$4"
  local goos="${goplat%%_*}" goarch="${goplat##*_}"
  cat >"${dir}/embed_${goplat}.go" <<EOF
//go:build ${goos} && ${goarch} && !libd2_nolib

// Code generated by scripts/go-sync-natives.sh. DO NOT EDIT.

package $(basename "$dir")

import (
	_ "embed"

	"github.com/libd2/go/internal/lib"
)

//go:embed natives/${goplat}/${libfile}.gz
var embeddedLibrary []byte

func init() { lib.Embed("${cname}", embeddedLibrary) }
EOF
}

install_one() {
  local pkgdir="$1" goplat="$2" cname="$3" src="$4"
  local libfile; libfile="$(libfile_for "$goplat" "$cname")"
  mkdir -p "${pkgdir}/natives/${goplat}"
  local out="${pkgdir}/natives/${goplat}/${libfile}"
  cp "$src" "$out"
  # ELF carries debug info that triples its size, and this binary is compiled into every
  # consumer's own executable. GNU strip only understands the HOST architecture, so on an x86_64
  # runner it silently leaves every arm/riscv build unstripped; llvm-strip handles them all.
  # Never fatal, but say so rather than embedding 8 MB quietly.
  local stripped=""
  for tool in llvm-strip llvm-strip-20 llvm-strip-19 llvm-strip-18 llvm-strip-17 llvm-strip-16 strip; do
    command -v "$tool" >/dev/null 2>&1 || continue
    if "$tool" "$out" 2>/dev/null; then stripped="$tool"; break; fi
  done
  [ -z "$stripped" ] && echo "go-sync-natives: WARNING could not strip ${libfile} for ${goplat}; embedding it unstripped"

  # Gzip what actually gets embedded. It roughly halves both the module and every consumer's
  # binary, and costs one decompression the first time a version runs on a machine — the library
  # is written to the cache directory either way. -n keeps the name and mtime out, so the same
  # input always produces the same bytes and a rebuild is not a diff.
  local raw; raw=$(wc -c <"$out")
  gzip -9 -n -c "$out" >"${out}.gz"
  rm -f "$out"

  emit_embed "$pkgdir" "$goplat" "$cname" "$libfile"
  echo "go-sync-natives: ${cname} ${goplat} ($(( raw / 1024 )) KB -> $(( $(wc -c <"${out}.gz") / 1024 )) KB gzipped)"
}

# Start from a clean slate so a platform dropped from the matrix does not linger as a stale
# binary that go:embed would happily keep shipping.
for entry in "${subsystems[@]}"; do
  IFS=: read -r _ godir _ <<<"$entry"
  rm -rf "${gomod}/${godir}/natives"
  rm -f "${gomod}/${godir}"/embed_*.go
done

found=0

if [ "${1:-}" = "--local" ]; then
  # Whatever the host just built. `uname` is enough here: this mode exists to run the Go tests
  # against a working tree, not to produce a release.
  case "$(uname -s)" in
    Darwin) goos=darwin ;;
    Linux)  goos=linux ;;
    FreeBSD) goos=freebsd ;;
    *) echo "go-sync-natives: unsupported host $(uname -s)" >&2; exit 1 ;;
  esac
  case "$(uname -m)" in
    arm64|aarch64) goarch=arm64 ;;
    x86_64|amd64)  goarch=amd64 ;;
    *) echo "go-sync-natives: unsupported host arch $(uname -m)" >&2; exit 1 ;;
  esac
  goplat="${goos}_${goarch}"

  for entry in "${subsystems[@]}"; do
    IFS=: read -r pkg godir cname <<<"$entry"
    src="$(ls "${repo_root}/packages/${pkg}/zig-out/lib/lib${cname}."{dylib,so} 2>/dev/null | head -1 || true)"
    if [ -z "$src" ]; then
      echo "go-sync-natives: no local build for ${cname} — run: (cd packages/${pkg} && zig build -Doptimize=ReleaseFast)" >&2
      continue
    fi
    install_one "${gomod}/${godir}" "$goplat" "$cname" "$src"
    found=$((found + 1))
  done
else
  artifacts_root="${1:?usage: go-sync-natives.sh --local | <artifacts-root>}"
  for entry in "${subsystems[@]}"; do
    IFS=: read -r pkg godir cname <<<"$entry"
    for tdir in "${artifacts_root}/${pkg}"/*/; do
      [ -d "$tdir" ] || continue
      triple="$(basename "$tdir")"
      goplat="$(goplat_for "$triple")"
      [ -n "$goplat" ] || continue
      src="$(ls "${tdir}lib/lib${cname}."{so,dylib} "${tdir}bin/${cname}.dll" 2>/dev/null | head -1 || true)"
      [ -n "$src" ] || continue
      install_one "${gomod}/${godir}" "$goplat" "$cname" "$src"
      found=$((found + 1))
    done
  done
fi

[ "$found" -gt 0 ] || { echo "go-sync-natives: nothing installed — refusing to leave the module without a binary" >&2; exit 1; }
echo "go-sync-natives: ${found} libraries installed"
