//! MPQ — the Blizzard archive every 1.14d asset ships inside, read-only, no dependencies.
//!
//! An archive is a 32-byte header, a hash table that maps a filename to a block, and a block
//! table that says where the bytes are and how they are packed. Both tables are encrypted with
//! the key derived from their own name, and a member is stored in `sector_size` chunks fronted
//! by a table of offsets — so reading one file is: hash the name, walk the hash table, decrypt
//! the sector offsets, then decrypt and explode each sector.
//!
//! Protected archives (the ones inside a `D2Patch_*.exe` / `LODPatch_*.exe` stub) strip the
//! hash table down to nothing and set `MPQ_FILE_FIX_KEY`, so a member's key depends on a name
//! the archive no longer carries. `recoverKey` gets it back anyway: the first dword of the
//! sector-offset table is always the table's own length, which is a known plaintext, and only
//! 256 keys can produce the observed ciphertext. See `Archive.recoverKey`.
//!
//! Every read takes a caller-supplied allocator and borrows the archive bytes; nothing here
//! touches the filesystem.

const std = @import("std");
const pkware = @import("pkware.zig");

pub const Error = pkware.Error || error{
    NotAnArchive,
    BadHeader,
    Truncated,
    NoSuchFile,
    NoSuchBlock,
    BadSectorTable,
    UnsupportedCompression,
};

pub const signature = "MPQ\x1a";

/// Which of the four hash flavours to compute. The seed row into the crypt table is the
/// only thing that differs.
pub const HashType = enum(u32) {
    /// Where in the hash table a name starts probing.
    table_offset = 0,
    /// The two halves of the stored name check.
    name_a = 1,
    name_b = 2,
    /// The base file encryption key, and the key the two tables are encrypted with.
    file_key = 3,
};

pub const Flags = struct {
    pub const implode: u32 = 0x0000_0100;
    pub const compress: u32 = 0x0000_0200;
    pub const encrypted: u32 = 0x0001_0000;
    pub const fix_key: u32 = 0x0002_0000;
    pub const patch_file: u32 = 0x0010_0000;
    pub const single_unit: u32 = 0x0100_0000;
    pub const delete_marker: u32 = 0x0200_0000;
    pub const sector_crc: u32 = 0x0400_0000;
    pub const exists: u32 = 0x8000_0000;

    /// The bits that mean "these bytes are not the file's bytes".
    pub const any_compression: u32 = implode | compress;
};

/// The mask byte a `compress` sector carries. Only pkware and zlib appear in a 1.14d archive;
/// the audio codecs are for the `.wav` members nothing here reads.
pub const Compression = struct {
    pub const huffman: u8 = 0x01;
    pub const zlib: u8 = 0x02;
    pub const pkware: u8 = 0x08;
    pub const bzip2: u8 = 0x10;
    pub const sparse: u8 = 0x20;
    pub const adpcm_mono: u8 = 0x40;
    pub const adpcm_stereo: u8 = 0x80;
};

const empty_block: u32 = 0xFFFF_FFFF;
const deleted_block: u32 = 0xFFFF_FFFE;

/// The 0x500-entry table every MPQ hash and cipher is driven from, generated by the same
/// LCG Storm seeds it with.
pub const crypt_table: [0x500]u32 = blk: {
    @setEvalBranchQuota(20000);
    var t: [0x500]u32 = @splat(0);
    var seed: u32 = 0x0010_0001;
    for (0..0x100) |i| {
        var idx = i;
        for (0..5) |_| {
            seed = (seed *% 125 +% 3) % 0x2AAAAB;
            const hi = (seed & 0xFFFF) << 16;
            seed = (seed *% 125 +% 3) % 0x2AAAAB;
            t[idx] = hi | (seed & 0xFFFF);
            idx += 0x100;
        }
    }
    break :blk t;
};

/// Names are matched case-insensitively and a forward slash is a backslash.
fn normalize(c: u8) u8 {
    if (c == '/') return '\\';
    return std.ascii.toUpper(c);
}

pub fn hashString(name: []const u8, ty: HashType) u32 {
    var s1: u32 = 0x7FED_7FED;
    var s2: u32 = 0xEEEE_EEEE;
    for (name) |raw| {
        const c: u32 = normalize(raw);
        s1 = crypt_table[(@intFromEnum(ty) << 8) + c] ^ (s1 +% s2);
        s2 = c +% s1 +% s2 +% (s2 << 5) +% 3;
    }
    return s1;
}

/// Decrypt in place over whole dwords; a trailing partial dword is left alone, exactly as
/// Storm leaves it.
pub fn decrypt(data: []u8, key_in: u32) void {
    var key = key_in;
    var seed: u32 = 0xEEEE_EEEE;
    var i: usize = 0;
    while (i + 4 <= data.len) : (i += 4) {
        seed +%= crypt_table[0x400 + (key & 0xFF)];
        const v = std.mem.readInt(u32, data[i..][0..4], .little) ^ (key +% seed);
        std.mem.writeInt(u32, data[i..][0..4], v, .little);
        key = ((~key << 0x15) +% 0x1111_1111) | (key >> 0x0B);
        seed = v +% seed +% (seed << 5) +% 3;
    }
}

/// The inverse of `decrypt`, so a test (or a writer) can produce bytes this module reads back.
pub fn encrypt(data: []u8, key_in: u32) void {
    var key = key_in;
    var seed: u32 = 0xEEEE_EEEE;
    var i: usize = 0;
    while (i + 4 <= data.len) : (i += 4) {
        seed +%= crypt_table[0x400 + (key & 0xFF)];
        const plain = std.mem.readInt(u32, data[i..][0..4], .little);
        std.mem.writeInt(u32, data[i..][0..4], plain ^ (key +% seed), .little);
        key = ((~key << 0x15) +% 0x1111_1111) | (key >> 0x0B);
        seed = plain +% seed +% (seed << 5) +% 3;
    }
}

pub const Header = struct {
    header_size: u32,
    archive_size: u32,
    format_version: u16,
    block_size: u16,
    hash_table_pos: u32,
    block_table_pos: u32,
    hash_table_len: u32,
    block_table_len: u32,

    pub const encoded_len = 32;

    pub fn parse(bytes: []const u8) Error!Header {
        if (bytes.len < encoded_len) return Error.Truncated;
        if (!std.mem.eql(u8, bytes[0..4], signature)) return Error.NotAnArchive;
        const h: Header = .{
            .header_size = std.mem.readInt(u32, bytes[4..8], .little),
            .archive_size = std.mem.readInt(u32, bytes[8..12], .little),
            .format_version = std.mem.readInt(u16, bytes[12..14], .little),
            .block_size = std.mem.readInt(u16, bytes[14..16], .little),
            .hash_table_pos = std.mem.readInt(u32, bytes[16..20], .little),
            .block_table_pos = std.mem.readInt(u32, bytes[20..24], .little),
            .hash_table_len = std.mem.readInt(u32, bytes[24..28], .little),
            .block_table_len = std.mem.readInt(u32, bytes[28..32], .little),
        };
        if (h.header_size < encoded_len) return Error.BadHeader;
        if (h.block_size > 23) return Error.BadHeader;
        return h;
    }

    pub fn sectorSize(self: Header) u32 {
        return @as(u32, 512) << @intCast(self.block_size);
    }
};

pub const HashEntry = struct {
    name_a: u32,
    name_b: u32,
    locale: u16,
    platform: u16,
    block_index: u32,

    pub fn isFree(self: HashEntry) bool {
        return self.block_index == empty_block or self.block_index == deleted_block;
    }
};

pub const BlockEntry = struct {
    /// Relative to the archive header, not to the file the archive was carved out of.
    file_pos: u32,
    packed_size: u32,
    unpacked_size: u32,
    flags: u32,

    pub fn isCompressed(self: BlockEntry) bool {
        return self.flags & Flags.any_compression != 0;
    }
};

pub const Archive = struct {
    /// The whole file, borrowed. `base` is where the header starts inside it.
    bytes: []const u8,
    base: u32,
    header: Header,
    hashes: []HashEntry,
    blocks: []BlockEntry,

    /// Take a decrypted table copy of both tables. `bytes` must outlive the archive.
    pub fn open(gpa: std.mem.Allocator, bytes: []const u8) !Archive {
        const base = findHeader(bytes) orelse return Error.NotAnArchive;
        const header = try Header.parse(bytes[base..]);
        const sector = header.sectorSize();
        if (sector == 0) return Error.BadHeader;

        const hashes = try gpa.alloc(HashEntry, header.hash_table_len);
        errdefer gpa.free(hashes);
        {
            const raw = try slice(bytes, base + header.hash_table_pos, header.hash_table_len * 16);
            const buf = try gpa.dupe(u8, raw);
            defer gpa.free(buf);
            decrypt(buf, hashString("(hash table)", .file_key));
            for (hashes, 0..) |*e, i| {
                const r = buf[i * 16 ..][0..16];
                e.* = .{
                    .name_a = std.mem.readInt(u32, r[0..4], .little),
                    .name_b = std.mem.readInt(u32, r[4..8], .little),
                    .locale = std.mem.readInt(u16, r[8..10], .little),
                    .platform = std.mem.readInt(u16, r[10..12], .little),
                    .block_index = std.mem.readInt(u32, r[12..16], .little),
                };
            }
        }

        const blocks = try gpa.alloc(BlockEntry, header.block_table_len);
        errdefer gpa.free(blocks);
        {
            const raw = try slice(bytes, base + header.block_table_pos, header.block_table_len * 16);
            const buf = try gpa.dupe(u8, raw);
            defer gpa.free(buf);
            decrypt(buf, hashString("(block table)", .file_key));
            for (blocks, 0..) |*e, i| {
                const r = buf[i * 16 ..][0..16];
                e.* = .{
                    .file_pos = std.mem.readInt(u32, r[0..4], .little),
                    .packed_size = std.mem.readInt(u32, r[4..8], .little),
                    .unpacked_size = std.mem.readInt(u32, r[8..12], .little),
                    .flags = std.mem.readInt(u32, r[12..16], .little),
                };
            }
        }

        return .{ .bytes = bytes, .base = base, .header = header, .hashes = hashes, .blocks = blocks };
    }

    pub fn deinit(self: *Archive, gpa: std.mem.Allocator) void {
        gpa.free(self.hashes);
        gpa.free(self.blocks);
        self.* = undefined;
    }

    pub fn sectorSize(self: Archive) u32 {
        return self.header.sectorSize();
    }

    /// The block index a name resolves to, by probing from its table-offset hash.
    pub fn lookup(self: Archive, name: []const u8) ?u32 {
        if (self.hashes.len == 0) return null;
        const mask = self.hashes.len - 1;
        const a = hashString(name, .name_a);
        const b = hashString(name, .name_b);
        var i: usize = hashString(name, .table_offset) & mask;
        for (0..self.hashes.len) |_| {
            const e = self.hashes[i];
            if (e.block_index == empty_block) return null;
            if (e.block_index != deleted_block and e.name_a == a and e.name_b == b) return e.block_index;
            i = (i + 1) & mask;
        }
        return null;
    }

    /// The decryption key for a named member. `fix_key` folds the block's position and size in,
    /// which is why a protected archive is unreadable without the name.
    pub fn fileKey(self: Archive, name: []const u8, index: u32) Error!u32 {
        if (index >= self.blocks.len) return Error.NoSuchBlock;
        const blk = self.blocks[index];
        // Only the base name is hashed, never the directory it sat in.
        const base_name = if (std.mem.lastIndexOfAny(u8, name, "\\/")) |at| name[at + 1 ..] else name;
        var key = hashString(base_name, .file_key);
        if (blk.flags & Flags.fix_key != 0) key = (key +% blk.file_pos) ^ blk.unpacked_size;
        return key;
    }

    /// Read a member by name. Caller owns the result.
    pub fn read(self: Archive, gpa: std.mem.Allocator, name: []const u8) ![]u8 {
        const index = self.lookup(name) orelse return Error.NoSuchFile;
        const blk = self.blocks[index];
        const key: ?u32 = if (blk.flags & Flags.encrypted != 0) try self.fileKey(name, index) else null;
        return self.readBlock(gpa, index, key);
    }

    /// Read a block directly. `key` is null for an unencrypted member, and for an encrypted one
    /// comes from `fileKey` (named) or `recoverKey` (nameless). Caller owns the result.
    pub fn readBlock(self: Archive, gpa: std.mem.Allocator, index: u32, key: ?u32) ![]u8 {
        if (index >= self.blocks.len) return Error.NoSuchBlock;
        const blk = self.blocks[index];
        if (blk.flags & Flags.delete_marker != 0) return Error.NoSuchBlock;
        const raw = try slice(self.bytes, self.base + blk.file_pos, blk.packed_size);

        const out = try gpa.alloc(u8, blk.unpacked_size);
        errdefer gpa.free(out);
        if (blk.unpacked_size == 0) return out;

        if (blk.flags & Flags.single_unit != 0) {
            const chunk = try gpa.dupe(u8, raw);
            defer gpa.free(chunk);
            if (key) |k| decrypt(chunk, k);
            _ = try expand(out, chunk, blk.flags);
            return out;
        }

        const sector = self.sectorSize();
        const count = (blk.unpacked_size + sector - 1) / sector;
        const offsets = try self.sectorOffsets(gpa, blk, key, count);
        defer gpa.free(offsets);

        var widest: usize = 0;
        for (0..count) |i| {
            if (offsets[i + 1] > raw.len or offsets[i] > offsets[i + 1]) return Error.BadSectorTable;
            widest = @max(widest, offsets[i + 1] - offsets[i]);
        }
        const buf = try gpa.alloc(u8, widest);
        defer gpa.free(buf);

        for (0..count) |i| {
            const src = raw[offsets[i]..offsets[i + 1]];
            const at = i * sector;
            const want = @min(@as(usize, sector), blk.unpacked_size - at);
            const chunk = buf[0..src.len];
            @memcpy(chunk, src);
            if (key) |k| decrypt(chunk, k +% @as(u32, @intCast(i)));
            _ = try expand(out[at..][0..want], chunk, blk.flags);
        }
        return out;
    }

    /// The sector offset table, decrypted. A stored (uncompressed) member has none, so one is
    /// synthesized from the fixed sector size.
    fn sectorOffsets(self: Archive, gpa: std.mem.Allocator, blk: BlockEntry, key: ?u32, count: usize) ![]u32 {
        if (!blk.isCompressed()) {
            const offs = try gpa.alloc(u32, count + 1);
            for (offs, 0..) |*o, i| o.* = @intCast(@min(i * self.sectorSize(), blk.packed_size));
            return offs;
        }
        // A sector-CRC member carries one extra entry past the end; it is read and ignored.
        const entries = count + 1 + @as(usize, if (blk.flags & Flags.sector_crc != 0) 1 else 0);
        const raw = try slice(self.bytes, self.base + blk.file_pos, entries * 4);
        const buf = try gpa.dupe(u8, raw);
        defer gpa.free(buf);
        if (key) |k| decrypt(buf, k -% 1);
        const offs = try gpa.alloc(u32, count + 1);
        errdefer gpa.free(offs);
        for (offs, 0..) |*o, i| o.* = std.mem.readInt(u32, buf[i * 4 ..][0..4], .little);
        if (offs[0] != entries * 4) return Error.BadSectorTable;
        return offs;
    }

    /// Recover a nameless `fix_key` member's key from its sector-offset table.
    ///
    /// The table's first dword is its own byte length, which is known before anything is
    /// decrypted. The cipher's first step is `plain ^ (key + 0xEEEEEEEE + crypt_table[0x400 + key
    /// & 0xFF])`, so guessing the key's low byte gives a candidate key directly — 256 of them,
    /// of which only the ones whose low byte agrees with the guess survive. Validating on the
    /// first dword alone finds false keys, so the whole table has to come out monotonic and end
    /// exactly at the block's packed size.
    pub fn recoverKey(self: Archive, gpa: std.mem.Allocator, index: u32) !?u32 {
        if (index >= self.blocks.len) return Error.NoSuchBlock;
        const blk = self.blocks[index];
        // Nothing to recover without an encrypted sector table to attack.
        if (blk.flags & Flags.encrypted == 0 or !blk.isCompressed()) return null;
        if (blk.flags & Flags.single_unit != 0 or blk.unpacked_size == 0) return null;

        const sector = self.sectorSize();
        const count = (blk.unpacked_size + sector - 1) / sector;
        const entries = count + 1 + @as(usize, if (blk.flags & Flags.sector_crc != 0) 1 else 0);
        const raw = try slice(self.bytes, self.base + blk.file_pos, entries * 4);
        const plain0: u32 = @intCast(entries * 4);
        const cipher0 = std.mem.readInt(u32, raw[0..4], .little);

        const buf = try gpa.alloc(u8, raw.len);
        defer gpa.free(buf);
        for (0..256) |b| {
            const seed = 0xEEEE_EEEE +% crypt_table[0x400 + b];
            const candidate = (cipher0 ^ plain0) -% seed;
            if (candidate & 0xFF != b) continue;
            @memcpy(buf, raw);
            decrypt(buf, candidate);
            var prev: u32 = 0;
            var ok = true;
            for (0..count + 1) |i| {
                const v = std.mem.readInt(u32, buf[i * 4 ..][0..4], .little);
                if (i == 0 and v != plain0) ok = false;
                if (i > 0 and v <= prev) ok = false;
                if (!ok) break;
                prev = v;
            }
            if (ok and prev == blk.packed_size) return candidate +% 1;
        }
        return null;
    }
};

/// Turn one packed chunk into exactly `dst.len` bytes.
fn expand(dst: []u8, src: []const u8, flags: u32) Error!usize {
    // Storm never stores a chunk that grew, so an equal size means it was left alone.
    if (src.len >= dst.len or flags & Flags.any_compression == 0) {
        if (src.len < dst.len) return Error.Truncated;
        @memcpy(dst, src[0..dst.len]);
        return dst.len;
    }
    if (flags & Flags.compress != 0) {
        if (src.len < 2) return Error.Truncated;
        return switch (src[0]) {
            Compression.pkware => pkware.explode(dst, src[1..]),
            Compression.zlib => inflate(dst, src[1..]),
            else => Error.UnsupportedCompression,
        };
    }
    return pkware.explode(dst, src);
}

fn inflate(dst: []u8, src: []const u8) Error!usize {
    const flate = std.compress.flate;
    var in = std.Io.Reader.fixed(src);
    var window: [flate.max_window_len]u8 = undefined;
    var d = flate.Decompress.init(&in, .zlib, &window);
    return d.reader.readSliceShort(dst) catch Error.Truncated;
}

/// A header can sit at any 512-byte boundary — an installer stub carries its archive appended.
fn findHeader(bytes: []const u8) ?u32 {
    var at: usize = 0;
    while (at + Header.encoded_len <= bytes.len) : (at += 512) {
        if (!std.mem.eql(u8, bytes[at..][0..4], signature)) continue;
        const hs = std.mem.readInt(u32, bytes[at + 4 ..][0..4], .little);
        if (hs >= Header.encoded_len) return @intCast(at);
    }
    return null;
}

fn slice(bytes: []const u8, at: u32, len: usize) Error![]const u8 {
    if (@as(usize, at) + len > bytes.len) return Error.Truncated;
    return bytes[at..][0..len];
}

// ---- tests ---------------------------------------------------------------------------------

const testing = std.testing;

test "crypt table and name hashes match Storm" {
    try testing.expectEqual(@as(u32, 0x55C6_36E2), crypt_table[0]);
    try testing.expectEqual(@as(u32, 0x02BE_0170), crypt_table[1]);
    try testing.expectEqual(@as(u32, 0xC3AF_3770), hashString("(hash table)", .file_key));
    try testing.expectEqual(@as(u32, 0xEC83_B3A3), hashString("(block table)", .file_key));
    // A path separator and case are both normalized away, so these are one name.
    const lower = hashString("data\\global\\excel\\armor.txt", .name_a);
    try testing.expectEqual(lower, hashString("DATA/Global/Excel/Armor.txt", .name_a));
}

test "encrypt and decrypt are inverses" {
    var buf = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0xAA };
    const original = buf;
    encrypt(&buf, 0x1234_5678);
    try testing.expect(!std.mem.eql(u8, &original, &buf));
    // The trailing partial dword is never touched.
    try testing.expectEqual(@as(u8, 0xAA), buf[12]);
    decrypt(&buf, 0x1234_5678);
    try testing.expectEqualSlices(u8, &original, &buf);
}

/// Assemble a real archive in memory so the reader is exercised end to end rather than against
/// a hand-written table.
const Builder = struct {
    gpa: std.mem.Allocator,
    data: std.ArrayList(u8) = .empty,
    blocks: std.ArrayList(BlockEntry) = .empty,
    names: std.ArrayList(?[]const u8) = .empty,
    block_size: u16 = 0,

    fn deinit(self: *Builder) void {
        self.data.deinit(self.gpa);
        self.blocks.deinit(self.gpa);
        self.names.deinit(self.gpa);
    }

    fn sector(self: Builder) usize {
        return @as(usize, 512) << @intCast(self.block_size);
    }

    /// Add a member stored sector-by-sector, each sector either raw or pkware-packed by
    /// `pack`. `name` null means the member gets no hash entry — a nameless block.
    fn add(self: *Builder, name: ?[]const u8, content: []const u8, packer: ?*const fn ([]u8, []const u8) []u8) !void {
        const at: u32 = @intCast(Header.encoded_len + self.data.items.len);
        const count = (content.len + self.sector() - 1) / self.sector();
        var offs = try self.gpa.alloc(u32, count + 1);
        defer self.gpa.free(offs);
        var body: std.ArrayList(u8) = .empty;
        defer body.deinit(self.gpa);
        offs[0] = @intCast((count + 1) * 4);
        var scratch: [4096]u8 = undefined;
        for (0..count) |i| {
            const chunk = content[i * self.sector() .. @min(content.len, (i + 1) * self.sector())];
            const stored = if (packer) |p| p(&scratch, chunk) else chunk;
            try body.appendSlice(self.gpa, if (stored.len < chunk.len) stored else chunk);
            offs[i + 1] = @intCast(offs[0] + body.items.len);
        }

        var flags: u32 = Flags.exists | Flags.compress | Flags.encrypted;
        if (name == null) flags |= Flags.fix_key;
        const blk: BlockEntry = .{
            .file_pos = at,
            .packed_size = offs[count],
            .unpacked_size = @intCast(content.len),
            .flags = flags,
        };
        // Only the base name is keyed, and fix_key folds file_pos and unpacked_size in on top.
        const full = name orelse "nameless.dll";
        const base_name = if (std.mem.lastIndexOfScalar(u8, full, '\\')) |sep| full[sep + 1 ..] else full;
        var key = hashString(base_name, .file_key);
        if (flags & Flags.fix_key != 0) key = (key +% blk.file_pos) ^ blk.unpacked_size;

        var table = try self.gpa.alloc(u8, (count + 1) * 4);
        defer self.gpa.free(table);
        for (offs, 0..) |o, i| std.mem.writeInt(u32, table[i * 4 ..][0..4], o, .little);
        encrypt(table, key -% 1);
        try self.data.appendSlice(self.gpa, table);

        var pos: usize = 0;
        for (0..count) |i| {
            const len = offs[i + 1] - offs[i];
            const enc = try self.gpa.dupe(u8, body.items[pos..][0..len]);
            defer self.gpa.free(enc);
            encrypt(enc, key +% @as(u32, @intCast(i)));
            try self.data.appendSlice(self.gpa, enc);
            pos += len;
        }

        try self.blocks.append(self.gpa, blk);
        try self.names.append(self.gpa, name);
    }

    /// Emit the finished archive: header, member payloads, hash table, block table.
    fn finish(self: *Builder, hash_len: u32) ![]u8 {
        const hash_pos: u32 = @intCast(Header.encoded_len + self.data.items.len);
        const block_pos: u32 = hash_pos + hash_len * 16;
        const total: u32 = block_pos + @as(u32, @intCast(self.blocks.items.len)) * 16;

        var out = try self.gpa.alloc(u8, total);
        errdefer self.gpa.free(out);
        @memset(out, 0);
        @memcpy(out[0..4], signature);
        std.mem.writeInt(u32, out[4..8], Header.encoded_len, .little);
        std.mem.writeInt(u32, out[8..12], total, .little);
        std.mem.writeInt(u16, out[12..14], 0, .little);
        std.mem.writeInt(u16, out[14..16], self.block_size, .little);
        std.mem.writeInt(u32, out[16..20], hash_pos, .little);
        std.mem.writeInt(u32, out[20..24], block_pos, .little);
        std.mem.writeInt(u32, out[24..28], hash_len, .little);
        std.mem.writeInt(u32, out[28..32], @intCast(self.blocks.items.len), .little);
        @memcpy(out[Header.encoded_len..][0..self.data.items.len], self.data.items);

        const hashes = out[hash_pos..][0 .. hash_len * 16];
        for (0..hash_len) |i| std.mem.writeInt(u32, hashes[i * 16 + 12 ..][0..4], empty_block, .little);
        for (self.names.items, 0..) |maybe, bi| {
            const name = maybe orelse continue;
            var at: usize = hashString(name, .table_offset) & (hash_len - 1);
            while (std.mem.readInt(u32, hashes[at * 16 + 12 ..][0..4], .little) != empty_block) {
                at = (at + 1) & (hash_len - 1);
            }
            std.mem.writeInt(u32, hashes[at * 16 ..][0..4], hashString(name, .name_a), .little);
            std.mem.writeInt(u32, hashes[at * 16 + 4 ..][0..4], hashString(name, .name_b), .little);
            std.mem.writeInt(u32, hashes[at * 16 + 12 ..][0..4], @intCast(bi), .little);
        }
        encrypt(hashes, hashString("(hash table)", .file_key));

        const blocks = out[block_pos..];
        for (self.blocks.items, 0..) |b, i| {
            std.mem.writeInt(u32, blocks[i * 16 ..][0..4], b.file_pos, .little);
            std.mem.writeInt(u32, blocks[i * 16 + 4 ..][0..4], b.packed_size, .little);
            std.mem.writeInt(u32, blocks[i * 16 + 8 ..][0..4], b.unpacked_size, .little);
            std.mem.writeInt(u32, blocks[i * 16 + 12 ..][0..4], b.flags, .little);
        }
        encrypt(blocks, hashString("(block table)", .file_key));
        return out;
    }
};

/// The blast reference stream, which unpacks to "AIAIAIAIAIAIA" — used as a pre-packed sector
/// so a test archive can carry a genuinely pkware-compressed member.
const ai_packed = [_]u8{ 0x08, 0x00, 0x04, 0x82, 0x24, 0x25, 0x8f, 0x80, 0x7f };
const ai_plain = "AIAIAIAIAIAIA";

fn packAi(out: []u8, chunk: []const u8) []u8 {
    std.debug.assert(std.mem.eql(u8, chunk, ai_plain));
    @memcpy(out[0..ai_packed.len], &ai_packed);
    return out[0..ai_packed.len];
}

fn buildFixture(gpa: std.mem.Allocator) ![]u8 {
    var b: Builder = .{ .gpa = gpa, .block_size = 0 };
    defer b.deinit();
    try b.add("data\\local\\hello.txt", ai_plain, packAi);
    try b.add("raw.bin", &pattern_600, null);
    try b.add(null, ai_plain, packAi);
    return b.finish(16);
}

const pattern_600: [600]u8 = blk: {
    var p: [600]u8 = undefined;
    for (&p, 0..) |*c, i| c.* = @intCast((i * 7 + 13) & 0xFF);
    break :blk p;
};

test "archive: header, tables and a pkware member" {
    const gpa = testing.allocator;
    const bytes = try buildFixture(gpa);
    defer gpa.free(bytes);

    var ar = try Archive.open(gpa, bytes);
    defer ar.deinit(gpa);

    try testing.expectEqual(@as(u32, 0), ar.base);
    try testing.expectEqual(@as(u32, 32), ar.header.header_size);
    try testing.expectEqual(@as(u32, 512), ar.sectorSize());
    try testing.expectEqual(@as(usize, 16), ar.hashes.len);
    try testing.expectEqual(@as(usize, 3), ar.blocks.len);

    try testing.expectEqual(@as(?u32, 0), ar.lookup("data\\local\\hello.txt"));
    // Case and separator normalization apply to the lookup too.
    try testing.expectEqual(@as(?u32, 0), ar.lookup("DATA/Local/HELLO.TXT"));
    try testing.expectEqual(@as(?u32, 1), ar.lookup("raw.bin"));
    try testing.expectEqual(@as(?u32, null), ar.lookup("nope.txt"));

    const hello = try ar.read(gpa, "data\\local\\hello.txt");
    defer gpa.free(hello);
    try testing.expectEqualStrings(ai_plain, hello);
}

test "archive: a stored multi-sector member comes back byte for byte" {
    const gpa = testing.allocator;
    const bytes = try buildFixture(gpa);
    defer gpa.free(bytes);
    var ar = try Archive.open(gpa, bytes);
    defer ar.deinit(gpa);

    const blk = ar.blocks[1];
    try testing.expectEqual(@as(u32, 600), blk.unpacked_size);
    try testing.expectEqual(Flags.exists | Flags.compress | Flags.encrypted, blk.flags);

    const raw = try ar.read(gpa, "raw.bin");
    defer gpa.free(raw);
    try testing.expectEqualSlices(u8, &pattern_600, raw);
}

test "archive: a nameless fix_key member is recovered by its sector table" {
    const gpa = testing.allocator;
    const bytes = try buildFixture(gpa);
    defer gpa.free(bytes);
    var ar = try Archive.open(gpa, bytes);
    defer ar.deinit(gpa);

    const blk = ar.blocks[2];
    try testing.expectEqual(Flags.exists | Flags.compress | Flags.encrypted | Flags.fix_key, blk.flags);
    // Nothing in the hash table points at it.
    for (ar.hashes) |h| try testing.expect(h.isFree() or h.block_index != 2);

    const key = (try ar.recoverKey(gpa, 2)) orelse return error.TestUnexpectedResult;
    const expected = (hashString("nameless.dll", .file_key) +% blk.file_pos) ^ blk.unpacked_size;
    try testing.expectEqual(expected, key);

    const data = try ar.readBlock(gpa, 2, key);
    defer gpa.free(data);
    try testing.expectEqualStrings(ai_plain, data);
}

test "archive: an appended header is found at its 512-byte boundary" {
    const gpa = testing.allocator;
    const inner = try buildFixture(gpa);
    defer gpa.free(inner);

    const stub = 512 * 3;
    const bytes = try gpa.alloc(u8, stub + inner.len);
    defer gpa.free(bytes);
    @memset(bytes[0..stub], 0x90);
    @memcpy(bytes[stub..], inner);

    var ar = try Archive.open(gpa, bytes);
    defer ar.deinit(gpa);
    try testing.expectEqual(@as(u32, stub), ar.base);
    const hello = try ar.read(gpa, "data\\local\\hello.txt");
    defer gpa.free(hello);
    try testing.expectEqualStrings(ai_plain, hello);
}

test "archive: rejects bytes that are not an archive" {
    const gpa = testing.allocator;
    try testing.expectError(Error.NotAnArchive, Archive.open(gpa, &[_]u8{0} ** 64));
    try testing.expectError(Error.NotAnArchive, Archive.open(gpa, "MPQ"));
    try testing.expectError(Error.Truncated, Header.parse("MPQ\x1a"));
}
